image: gitlab/dind:latest
services:
  - docker:dind

stages:
  - build
  - release
  - deploy

variables:
  CONTAINER_DEV_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

build:
  stage: build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --pull -t $CONTAINER_DEV_IMAGE .
    - docker push $CONTAINER_DEV_IMAGE
  only:
    - master
    - dev
  tags:
    - local

release-image:
  stage: release
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CONTAINER_DEV_IMAGE
    - docker tag $CONTAINER_DEV_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master
  tags:
    - local

deploy-development:
  stage: deploy
  only:
    - "dev"
  before_script:
    - eval "$(ssh-agent -s)"
    - ssh-add <(echo "$DEPLOY_SERVER_PRIVATE_KEY")
    - ssh-keyscan -H $DEVELOPMENT_SERVER_IP >> ~/.ssh/known_hosts
  script:
    - printf "\nSMTP_PASSWORD=${SMTP_PASSWORD}\nDB_PASSWORD=${DEVELOPMENT_DB_PASSWORD}\n" >> .env.development
    - ssh root@$DEVELOPMENT_SERVER_IP "mkdir -p /opt/nft/nft-market-b/public"
    - scp -r ./.env.development ./docker-compose.yml root@${DEVELOPMENT_SERVER_IP}:/opt/nft/nft-market-b/
    - ssh root@$DEVELOPMENT_SERVER_IP "cd /opt/nft/nft-market-b; sed -i 's/latest/dev/g' docker-compose.yml; mv -f .env.development .env; docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}; docker pull ${CONTAINER_DEV_IMAGE}; docker-compose up -d"
  tags:
    - local

deploy-production:
  stage: deploy
  only:
    - "master"
  before_script:
    - eval "$(ssh-agent -s)"
    - ssh-add <(echo "$DEPLOY_SERVER_PRIVATE_KEY")
    - ssh-keyscan -H $PRODUCTION_SERVER_IP >> ~/.ssh/known_hosts
  script:
    - printf "\nSMTP_PASSWORD=${SMTP_PASSWORD}\nDB_PASSWORD=${PRODUCTION_DB_PASSWORD}\n" >> .env.production
    - ssh root@$PRODUCTION_SERVER_IP "mkdir -p /opt/nft/nft-market-b/public"
    - scp -r ./.env.production ./docker-compose.yml root@${PRODUCTION_SERVER_IP}:/opt/nft/nft-market-b/
    - ssh root@$PRODUCTION_SERVER_IP "cd /opt/nft/nft-market-b; mv -f .env.production .env; docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}; docker pull ${CONTAINER_RELEASE_IMAGE}; docker-compose up -d"
  tags:
    - local