version: "3.7"
services:
    db:
        image: "postgres:11"
        container_name: nft-db
        environment:
            - POSTGRES_USER=nftuser
            - POSTGRES_PASSWORD=nftuser
            - POSTGRES_DB=nft
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - 5434:5432

volumes:
    pgdata:
