
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

import "IIO.sol";

contract gameObject is IIO {


    uint HP;
    int defend;
    address attacker; //может быть нужен массив?

    constructor(uint valueHP) public { 
        require(tvm.pubkey() != 0, 101);
        tvm.accept();

        HP = valueHP;
    }

    function getDefend(int value) public {
        tvm.accept();
        defend = defend + value;
    }


    //Разобрать косяк с адрессом
    function getAttack(uint value, address dest) public override {
        tvm.accept();

        attacker = dest;
        selfDestruction(value);
    }

    function selfDestruction(uint value) private {
        tvm.accept();

        if (HP < value) {
            //вызвать саморазрушение и удаление всех юнитов
            sendAllValueAndDestroyed();
        }
        else  {
            HP = HP - value;
        }
    }

    function sendAllValueAndDestroyed() private checkOwner() view {

        attacker.transfer(1, true, 128 + 32);
    }

      modifier checkOwner() {
		require(msg.pubkey() == tvm.pubkey(), 102);
        tvm.accept();
		_;
	}



}