
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

import "IIO.sol";

contract gameObject is IIO {


    int HP;
    int defend;
    address attacker; 

    constructor(int valueHP) public { 
        require(tvm.pubkey() != 0, 101);
        tvm.accept();
        
        HP = valueHP;
    }

    function getDefend(int value) virtual external override {
        tvm.accept();
        defend = defend + value;
    }


    function getAttack(int value) virtual external override {
        tvm.accept();

        attacker = msg.sender;
        HP = HP - value;
        checkDead();
    }

    function checkDead() private checkOwner()  {
        if (HP < 0) {
            sendAllValueAndDestroyed();
        }
    }

    function sendAllValueAndDestroyed() private checkOwner() {
        attacker.transfer(1, true, 128 + 32);
    }


     modifier checkOwner() {
		require(msg.pubkey() == tvm.pubkey(), 102);
        tvm.accept();
		_;
	}


}